language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t niallkenny/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true niallkenny/docker-react npm run test
